<?php

namespace App\Core\Support;

class CorePermissions
{
    /**
     * @return array<int, array{name: string, display_name: string, module: string, guard_name: string, is_system: bool}>
     */
    public static function definitions(): array
    {
        return [
            ['name' => 'core.users.view-any', 'display_name' => 'View users', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.users.create', 'display_name' => 'Create users', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.users.update', 'display_name' => 'Update users', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.users.delete', 'display_name' => 'Delete users', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.roles.view-any', 'display_name' => 'View roles', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.roles.create', 'display_name' => 'Create roles', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.roles.update', 'display_name' => 'Update roles', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.roles.delete', 'display_name' => 'Delete roles', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.permissions.view-any', 'display_name' => 'View permissions', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.permissions.update', 'display_name' => 'Update permissions', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.settings.manage', 'display_name' => 'Manage settings', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.company-profile.manage', 'display_name' => 'Manage company profile', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'core.audit-logs.view-any', 'display_name' => 'View audit logs', 'module' => 'Core', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.product-categories.view-any', 'display_name' => 'View product categories', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.product-categories.create', 'display_name' => 'Create product categories', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.product-categories.update', 'display_name' => 'Update product categories', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.product-categories.delete', 'display_name' => 'Delete product categories', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.units.view-any', 'display_name' => 'View units', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.units.create', 'display_name' => 'Create units', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.units.update', 'display_name' => 'Update units', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.units.delete', 'display_name' => 'Delete units', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.taxes.view-any', 'display_name' => 'View taxes', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.taxes.create', 'display_name' => 'Create taxes', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.taxes.update', 'display_name' => 'Update taxes', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.taxes.delete', 'display_name' => 'Delete taxes', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.products.view-any', 'display_name' => 'View products', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.products.create', 'display_name' => 'Create products', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.products.update', 'display_name' => 'Update products', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.products.delete', 'display_name' => 'Delete products', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.customers.view-any', 'display_name' => 'View customers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.customers.create', 'display_name' => 'Create customers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.customers.update', 'display_name' => 'Update customers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.customers.delete', 'display_name' => 'Delete customers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.suppliers.view-any', 'display_name' => 'View suppliers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.suppliers.create', 'display_name' => 'Create suppliers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.suppliers.update', 'display_name' => 'Update suppliers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.suppliers.delete', 'display_name' => 'Delete suppliers', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.warehouses.view-any', 'display_name' => 'View warehouses', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.warehouses.create', 'display_name' => 'Create warehouses', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.warehouses.update', 'display_name' => 'Update warehouses', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'master-data.warehouses.delete', 'display_name' => 'Delete warehouses', 'module' => 'MasterData', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'inventory.stock-movements.view-any', 'display_name' => 'View stock movements', 'module' => 'Inventory', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'inventory.stock-movements.create', 'display_name' => 'Create stock movements', 'module' => 'Inventory', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.view-any', 'display_name' => 'View sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.create', 'display_name' => 'Create sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.update', 'display_name' => 'Update sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.submit', 'display_name' => 'Submit sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.approve', 'display_name' => 'Approve sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-orders.cancel', 'display_name' => 'Cancel sales orders', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-deliveries.view-any', 'display_name' => 'View sales deliveries', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-deliveries.create', 'display_name' => 'Create sales deliveries', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-deliveries.confirm', 'display_name' => 'Confirm sales deliveries', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-invoices.view-any', 'display_name' => 'View sales invoices', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-invoices.create', 'display_name' => 'Create sales invoices', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-invoices.post', 'display_name' => 'Post sales invoices', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-receipts.view-any', 'display_name' => 'View sales receipts', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.sales-receipts.create', 'display_name' => 'Create sales receipts', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.view-any', 'display_name' => 'View quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.create', 'display_name' => 'Create quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.update', 'display_name' => 'Update quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.submit', 'display_name' => 'Submit quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.approve', 'display_name' => 'Approve quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.convert', 'display_name' => 'Convert quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'sales.quotations.cancel', 'display_name' => 'Cancel quotations', 'module' => 'Sales', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.view-any', 'display_name' => 'View purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.create', 'display_name' => 'Create purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.update', 'display_name' => 'Update purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.submit', 'display_name' => 'Submit purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.approve', 'display_name' => 'Approve purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-orders.cancel', 'display_name' => 'Cancel purchase orders', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-receipts.view-any', 'display_name' => 'View purchase receipts', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-receipts.create', 'display_name' => 'Create purchase receipts', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.purchase-receipts.confirm', 'display_name' => 'Confirm purchase receipts', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.supplier-bills.view-any', 'display_name' => 'View supplier bills', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.supplier-bills.create', 'display_name' => 'Create supplier bills', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.supplier-bills.post', 'display_name' => 'Post supplier bills', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.supplier-payments.view-any', 'display_name' => 'View supplier payments', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'purchasing.supplier-payments.create', 'display_name' => 'Create supplier payments', 'module' => 'Purchasing', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.chart-of-accounts.view-any', 'display_name' => 'View chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.chart-of-accounts.create', 'display_name' => 'Create chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.chart-of-accounts.update', 'display_name' => 'Update chart of accounts', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.journal-entries.view-any', 'display_name' => 'View journal entries', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.journal-entries.create', 'display_name' => 'Create journal entries', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'accounting.journal-entries.post', 'display_name' => 'Post journal entries', 'module' => 'Accounting', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.view', 'display_name' => 'View CRM records', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.create', 'display_name' => 'Create CRM records', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.edit', 'display_name' => 'Edit CRM records', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.delete', 'display_name' => 'Delete CRM records', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.export', 'display_name' => 'Export CRM data', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.assign', 'display_name' => 'Assign CRM leads and opportunities', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.convert_lead', 'display_name' => 'Convert CRM leads', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.move_stage', 'display_name' => 'Move CRM opportunity stages', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.complete_activity', 'display_name' => 'Complete CRM activities', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.manage_pipeline', 'display_name' => 'Manage CRM pipeline', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.manage_sources', 'display_name' => 'Manage CRM lead sources', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.manage_rules', 'display_name' => 'Manage CRM assignment rules', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
            ['name' => 'crm.view_reports', 'display_name' => 'View CRM reports', 'module' => 'CRM', 'guard_name' => 'web', 'is_system' => true],
        ];
    }
}
